services:
  postgres:
    image: postgres
    container_name: postgresdb
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  api:
    build: 
      context: .
      dockerfile: dockerfile.api
    container_name: nest-api
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://pedrodb:drope007@postgres:5432/nestdb
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    command: sh -c "npx prisma migrate deploy && npm run start:prod"